### ISSUE TITLE
Where should we locate Hawtio v1 original core plugin features?

### ISSUE THREAD

**Issue by tadayosi** [hawtio/hawtio-core#12]
In Hawtio v1 there are a few useful plugin features as the core:
https://github.com/hawtio/hawtio/tree/master/hawtio-web/src/main/webapp/app/core/html
To name a few, there are:

- Login
- Welcome
- Preference
- Branding
- Help

features, but I couldn't find them in existing Hawtio v2 components. Where should we port them to?  `hawtio-core-navigation` or `hawtio-core-perspective`?  Or else should we create a new project for accommodating them?

**Comment by gashcrumb** [comment]
There's hawtio-preferences -> https://github.com/hawtio/hawtio-preferences

the other ones don't (yet) have a v2 equivalent.  For the login stuff I'd probably defer to keycloak/oauth.

As far as the Welcome plugin goes, there's strategies in hawtio-core-navigation for figuring out what nav item should take precedence when you first go into the console, plugins can specify `defaultPage` in their nav item, the camel/activemq plugins in hawtio-integration do this I believe:

https://github.com/hawtio/hawtio-core-dts/blob/master/hawtio-core-navigation.d.ts#L64

**Comment by tadayosi** [comment]
OK, thanks!  For record, I've created following tickets:
https://issues.jboss.org/browse/ENTESB-6489
https://issues.jboss.org/browse/ENTESB-6490
https://issues.jboss.org/browse/ENTESB-6491
https://issues.jboss.org/browse/ENTESB-6492

**Comment by gashcrumb** [comment]
Great!  Think this is all set.
