### ISSUE TITLE
hawtio-core LOGGER obscures log messages

### ISSUE THREAD

**Issue by benjaminapetersen** [hawtio/hawtio-core#13]
https://github.com/hawtio/hawtio-core/blob/master/dist/hawtio-core.js#L83

results in logs like this:

```javascript 
 drops valueFrom from the entry.... hawtio-core.js:83
```

You can do a little bit with `.bind.call` to work around this type of issue:

```javascript
// example
window.myLog = Function.prototype.bind.call(console.log, console);

// other file:
myLog('foo');   // log will reference this location, as expected
```

**Comment by gashcrumb** [comment]
Good call!  Any chance you could submit a PR for this?  Thanks!

**Comment by benjaminapetersen** [comment]
Sure, got any contributing docs? Noticed the `src` doesn't appear in the repo, don't think there is a `CONTRIBUTING.md` file.

**Comment by gashcrumb** [comment]
Yeah, we need to work on that :-) but the basic gist is on this page under Getting Started http://hawt.io/overview/index.html

**Comment by alexkieling** [comment]
@benjaminapetersen is this still an issue?

**Comment by benjaminapetersen** [comment]
@akieling I have not addressed this issue yet, & don't see any other PR mentions here, so I assume it lingers.

**Comment by alexkieling** [comment]
Closing old issue.
