### ISSUE TITLE
Bower support dropped

### ISSUE THREAD

**Issue by benjaminapetersen** [hawtio/hawtio-core#15]
I'm not certain when bower support was dropped, but we still use `bower` in the openshift web console & can't pull updated versions.   Ideally this would have been noted in release notes w/a timetable to move to npm/yarn.  Possible to get a `bower.json` file back?

**Comment by benjaminapetersen** [comment]
Btw, its fine to use both npm & bower, they don't need to be exclusive.

**Comment by tadayosi** [comment]
Bower support was dropped for hawtio-* 3.x components. As far as I know, OpenShift Web Console still uses 2.x branches, which I believe still doesn't switch from bower to npm/yarn. Check the `2.x-patch` branch.

**Comment by tadayosi** [comment]
FYI, it's my understanding that hawtio v2 (in contrast to hawtio/hawtio 1.x versions) has two branches right now: 2.x (2.x-patch) and 3.0.x (master). `2.x-patch` is a maintenance branch and is mostly dedicated to OpenShift Web Console. On the other hand, we currently actively develop `master` branch (i.e. 3.0.x), which is targeted to the coming Fuse 7 and will have destructive changes such as migration to npm/yarn, etc.

"hawtio v2" is the umbrella word/branding name for various hawtio-* 2+ components such as hawtio-core, hawtio-ui, hawtio-jmx, or hawtio-integration.

**Comment by benjaminapetersen** [comment]
Right. This is a bit confusing.  We are trying to resolve the other issue I created re:Protractor testing.  Considering upgrading, but im not completely clear on what would break moving to v3, and it is bower isn't supported. Thus, this issue.  It would be useful & fairly simple to throw a `bower.json` back in the repo. 

We may move away form `bower` in the future as some seem to be doing, but it will require some tooling updates that we aren't working on right now.

**Comment by benjaminapetersen** [comment]
After all, the project description, top of the github page:

     The core plugin discovery and bootstrapping mechanism for hawtio as a bower package

😄

**Comment by tadayosi** [comment]
Good catch. I still don't have a permission to change the line.

@akieling Could you update it? (Or give me admin right :-) )

**Comment by akieling** [comment]
Can we close this issue?

**Comment by benjaminapetersen** [comment]
We are not dropping bower in the short term if that helps.  Long term, perhaps.

**Comment by akieling** [comment]
We won't drop support for Bower in the 2.x-patch branch and we can add support to it in the master branch in the future if required. How does that sound? @tadayosi @astefanutti

**Comment by tadayosi** [comment]
@akieling So long as being technically possible to have npm and bower at the same time, I'm fine with it. We may just need to make sure we won't forget to publish a new version for bower as well as npm.

@benjaminapetersen Btw, bower is already deprecated and can be disabled anytime soon. 

https://bower.io
> ...psst! While Bower is maintained, we recommend using Yarn and Webpack for front-end projects read how to migrate!

Will you still want to rely on bower for OpenShift Web Console even so?

**Comment by akieling** [comment]
Are we all happy with supporting Bower in the 2.x-patch branch (the one used to build the JVM console) and postpone adding support for it in the master branch until we really need it?

**Comment by astefanutti** [comment]
@akieling sounds good to me.

**Comment by tadayosi** [comment]
@akieling yes. thanks.

**Comment by benjaminapetersen** [comment]
Works for me, this is for the most part trivial.
