### ISSUE TITLE
Consider adding tests

### ISSUE THREAD

**Issue by benjaminapetersen** [hawtio/hawtio-core#16]
Since this module alter's angular's core bootstrapping features, it would be nice if it was covered by tests to ensure stability across updates.

**Comment by tadayosi** [comment]
I agree that hawtio v2 should have more tests. Contributions are always welcome btw :-)

**Comment by benjaminapetersen** [comment]
I'd def be more likely to jump on that if it had any tests / a testing framework setup.  Guessing someone more core might want to do the initial setup?

**Comment by akieling** [comment]
I configured Karma and Jasmine to run unit tests. The code that does the bootstrapping might need some refactoring before it can be properly unit tested.

**Comment by benjaminapetersen** [comment]
Confused -- why close this then if there are still no tests?

**Comment by benjaminapetersen** [comment]
Maybe.  Testing is a big task.  Not sure if that's one issue or many, but could list test needs in order of priority.  Each module probably needs a set of tests. 

My inspiration for opening the issue comes from the pain points we have had trying to get our e2e test running (and keep them running) despite the altered bootstrapping of angular.  Would be great if this repo was tested & could prove that test for other projects can remain stable despite the changes to bootstrapping (and perhaps give some direction).

**Comment by alexkieling** [comment]
Some colleagues plan to add e2e tests to hawtio/hawtio.
