### ISSUE TITLE
Upgrade to jQuery 3.0

### ISSUE THREAD

**Issue by alexkieling** [hawtio/hawtio-core#20]
Upgrade to jQuery 3.0 following the documentation below:
https://jquery.com/upgrade-guide/3.0/
https://github.com/jquery/jquery-migrate

Test all features of hawtio-jmx and hawtio-integration.

**Comment by akieling** [comment]
[hawtio-jmx](https://github.com/hawtio/hawtio-jmx) depends on [patternfly-bootstrap-treeview](https://github.com/patternfly/patternfly-bootstrap-treeview) and it breaks when jQuery is upgrade to v3. I created an [issue](https://github.com/patternfly/patternfly-bootstrap-treeview/issues/65) on their project to fix this issue.

**Comment by alexkieling** [comment]
It looks like patternfly-bootstrap-treeview will never upgrade to jQuery 3 and hawtio would need to move to another tree component to be able to upgrade to jQuery 3.

**Comment by alexkieling** [comment]
Not upgrading to jQuery 3 due to dependency on patternfly-bootstrap-treeview.
