### ISSUE TITLE
User & Help menu icons disappear when browser window is narrowed

### ISSUE THREAD

**Issue by tadayosi** [hawtio/hawtio-core#27]
Normal:

![screen shot 2018-03-14 at 13 17 30](https://user-images.githubusercontent.com/156692/37383189-73ecb0d0-278a-11e8-9f60-a40944a967c6.png)

When browser window is narrowed:

![screen shot 2018-03-14 at 13 17 42](https://user-images.githubusercontent.com/156692/37383192-7651f1be-278a-11e8-842c-bc3f0e6c57c7.png)

**Comment by alexkieling** [comment]
That behavior might be intended. I suggest getting in touch with the PatternFly team to clarify the issue.

**Comment by tadayosi** [comment]
@alexkieling I don't understand why you think it's a matter of PatternFly. If those icons disappear just because it behaves responsibly, it's ok but then we should still provide a way to access those menus in a collapsed view, shouldn't we?  PatternFly seems to provide such a way already:
https://rawgit.com/patternfly/patternfly/master-dist/dist/tests/basic.html
so I wouldn't say it's a matter of PatternFly's intended behaviour or not.

**Comment by tadayosi** [comment]
And I would also add that the current set of icons (help & user) is so minimalistic that I cannot see any value in behaving responsibly in this area. A small device should still show the top bar concisely with the current set of icons. So I'd say we should stop behaving responsibly in this area.

I'd say we can still maintain the icon set even when we decide to show the logged-in user name with the user icon.

**Comment by alexkieling** [comment]
I agree with your points and asked why the Help and User dropdowns are hidden on small screens but don't show up anywhere else. They said it's the app responsibility to dynamically add new entries to the vertical navigation. See the [Vertical Navigation design documentation](http://www.patternfly.org/pattern-library/navigation/vertical-navigation/#design) where they talk about responsive states.
I think the component should support both hiding the dropdowns and showing the vertical nav items. It's currently only doing half of the job.
We have two options:
- try to override the CSS on Hawtio and never hide the dropdowns
- Angular PatternFly component has an `ignoreMobile` parameter that could be used to avoid hiding the dropdowns
- discuss with the PatternFly team and contribute changes to PatternFly CSS and Angular PatternFly component to make it work properly
- implement the logic that dynamically adds items to the vertical menu on Hawtio

**Comment by alexkieling** [comment]
I've added an issue to Angular PatternFly.
https://github.com/patternfly/angular-patternfly/issues/745

**Comment by tadayosi** [comment]
Thanks for the explanation. Then I'm still not convinced that PatternFly needs a fix. To me, the problem is that Hawtio isn't following the design guideline on the masthead responsiveness in the vertical nav. The OpenShift web console already follows it, and it moves 'About' and 'Logout' items into the collapsed menu for a smaller device. Why don't we adopt the same design to Hawtio's masthead?

**Comment by tadayosi** [comment]
In the same context, I can say that the current vertical nav design of Hawtio v2 isn't responsive; if you see the console in a smaller window, it displays it uglily. I now understand that this should be what we really need to address here.

**Comment by alexkieling** [comment]
PatternFly is fine but I think the Angular PatternFly vertical navigation component could handle showing the hidden items on small screens.

**Comment by tadayosi** [comment]
I see. Besides, the Hawtio logo also disapppears when window is narrowed. Is that also something that should be handled at Angular PatternFly side?
