### ISSUE TITLE
Introduce semantic-release for releasing versions

### ISSUE THREAD

**Issue by tadayosi** [hawtio/hawtio-core#28]
We've already started following [AngularJS commit guidelines](https://github.com/angular/angular.js/blob/master/DEVELOPERS.md#-git-commit-guidelines). Let's move one step further and automate versioning using [semantic-release](https://semantic-release.gitbooks.io/semantic-release/content/#highlights) tool.

**Comment by alexkieling** [comment]
@tadayosi do you still think it's worth the effort?

**Comment by tadayosi** [comment]
@alexkieling Depending on how Hawtio.next will be shaped, it's still good idea to me to consider utilising a tool like semantic-release to ease our future releases.
