### ISSUE TITLE
Navbar not updated when item validity state changes

### ISSUE THREAD

**Issue by jamesnetherton** [hawtio/hawtio-core#30]
Navbar items expose the option of providing a validity check function via an `isValid` property.

Seems this is only respected when the Navbar is first rendered. Thus whenever the result of the `isValid` function changes, the navbar is not updated to reflect this.

For example, run the hawtio-integration project master branch against a container such as Karaf or EAP. Then deploy a Camel application. Notice that the Camel navbar item never appears, you have to refresh the page.

**Comment by alexkieling** [comment]
Yep, we are not watching for changes to the result of that function and re-rendering the main navigation. If that's required, then we'll need to implement it. Hopefully, it won't hurt performance too much.

**Comment by astefanutti** [comment]
FWIW, similar issue has been addressed for preferences panels in 5b3a034c0755a715a3585d868883209c8180da25:

https://github.com/hawtio/hawtio-core/blob/5b3a034c0755a715a3585d868883209c8180da25/src/app/preferences/preferences-home/preferences-home.controller.ts#L16-L22

**Comment by alexkieling** [comment]
@jamesnetherton Please test it. You'll need to yarn link from hawtio-integration to test Camel.

**Comment by jamesnetherton** [comment]
The basic functionality looks good. Visibility of the Camel tab is correctly toggled when I start / stop a test Camel application. However, I noticed one issue. 

If you activate a Camel application whilst on any of the OSGi, Runtime or Diagnostics pages, when the Camel tab eventually appears, the main page content disappears and you're left staring at a mostly empty page.

**Comment by alexkieling** [comment]
@jamesnetherton Please test hawtio-integration again. No need to link projects. I've updated the dependencies.

**Comment by jamesnetherton** [comment]
Working fine now, thanks! :1st_place_medal:
