### ISSUE TITLE
Only display logout menu item if required

### ISSUE THREAD

**Issue by jamesnetherton** [hawtio/hawtio-core#32]
If you run Hawtio with authentication disabled, the logout menu item is redundant, so I think it'd be better to not display it if possible.

**Comment by tadayosi** [comment]
I thought I implemented it before in hawtio-console-assembly; I only enabled the logout menu when it's already logged in. So I think it's a bug or something broke it.

**Comment by jamesnetherton** [comment]
Yes, you're right. I cloned it here https://github.com/hawtio/hawtio/issues/2527.
