### ISSUE TITLE
Wrap module in an IIFE

### ISSUE THREAD

**Issue by benjaminapetersen** [hawtio/hawtio-core#7]
As we are using hawtio in the openshift console, I'd like to see the module wrapped in an IIFE just to help ensure some of the work done in the global namespace doesn't clobber anything else.

```javascript
(function() {
  'use strict';
  // hawtio code here!
})();
```

**Comment by benjaminapetersen** [comment]
I'd be potentially up for helping with a PR for this, but will wait for comments in case anyone sees a prob with the idea.

**Comment by gashcrumb** [comment]
Yeah, been meaning long-term to switch the code here over to typescript, kind of like [on this experimental branch](https://github.com/hawtio/hawtio-core/tree/3.x/plugins/core/ts) which will accomplish among other things the same result.  But certainly before that happens this is worth doing.  We do need to make sure the `hawtioPluginLoader` and `HawtioCore` objects are exported to the global namespace, effectively we need to maintain this contract -> https://github.com/hawtio/hawtio-core-dts/blob/master/hawtio-core.d.ts

**Comment by alexkieling** [comment]
`hawtioPluginLoader` and `HawtioCore` are currently being initialized in IIFEs. Shouldn`t the log initialization stuff be encapsulated in an IIFE as well?

**Comment by gashcrumb** [comment]
@alexkieling +1

**Comment by benjaminapetersen** [comment]
Agree!
