### ISSUE TITLE
npm package

### ISSUE THREAD

**Issue by gashcrumb** [hawtio/hawtio-core#8]
We should migrate the hawtio-\* packages from bower to npm I think, starting here, which will mean then we just have one install command for dependencies etc.

@kahboom FYI

**Comment by gashcrumb** [comment]
Probably best to increment the major version for this one?

**Comment by gashcrumb** [comment]
Wonder actually if we need to do #9 first

**Comment by gashcrumb** [comment]
Also need a `yarn.lock` file, would also be good to start migrating gulp tasks to scripts in the `package.json`

**Comment by alexkieling** [comment]
@gashcrumb Without wiredep, there seems to be two paths to take:
- manually manage the `script` tags in `index.html`
- change the code to use a module system and use a module bundler

**Comment by alexkieling** [comment]
Migration to npm package done.
