### ISSUE TITLE
Switch code over to typescript

### ISSUE THREAD

**Issue by gashcrumb** [hawtio/hawtio-core#9]
It'd be worth investigating moving the existing code to typescript and start making use of the node.js module resolution stuff in typescript, will probably require implementing #8 first.

A bit of work on this has been done already [on this branch](https://github.com/hawtio/hawtio-core/tree/3.x)

**Comment by gashcrumb** [comment]
I think also it'd be good to get this building via webpack vs the current gulp tasks.

**Comment by alexkieling** [comment]
Converted project to typescript. The code refactoring can be done in another task.
